/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,vue}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Catppuccin Mocha (Dark)
        'ctp-rosewater': '#f5e0dc',
        'ctp-flamingo': '#f2cdcd',
        'ctp-pink': '#f5c2e7',
        'ctp-mauve': '#cba6f7',
        'ctp-red': '#f38ba8',
        'ctp-maroon': '#eba0ac',
        'ctp-peach': '#fab387',
        'ctp-yellow': '#f9e2af',
        'ctp-green': '#a6e3a1',
        'ctp-teal': '#94e2d5',
        'ctp-sky': '#89dceb',
        'ctp-sapphire': '#74c7ec',
        'ctp-blue': '#89b4fa',
        'ctp-lavender': '#b4befe',
        'ctp-text': '#cdd6f4',
        'ctp-subtext1': '#bac2de',
        'ctp-subtext0': '#a6adc8',
        'ctp-overlay2': '#9399b2',
        'ctp-overlay1': '#7f849c',
        'ctp-overlay0': '#6c7086',
        'ctp-surface2': '#585b70',
        'ctp-surface1': '#45475a',
        'ctp-surface0': '#313244',
        'ctp-base': '#1e1e2e',
        'ctp-mantle': '#181825',
        'ctp-crust': '#11111b',
        // Catppuccin Latte (Light)
        'ctp-light-rosewater': '#dc8a78',
        'ctp-light-flamingo': '#dd7878',
        'ctp-light-pink': '#ea76cb',
        'ctp-light-mauve': '#8839ef',
        'ctp-light-red': '#d20f39',
        'ctp-light-maroon': '#e64553',
        'ctp-light-peach': '#fe640b',
        'ctp-light-yellow': '#df8e1d',
        'ctp-light-green': '#40a02b',
        'ctp-light-teal': '#179299',
        'ctp-light-sky': '#04a5e5',
        'ctp-light-sapphire': '#209fb5',
        'ctp-light-blue': '#1e66f5',
        'ctp-light-lavender': '#7287fd',
        'ctp-light-text': '#4c4f69',
        'ctp-light-subtext1': '#5c5f77',
        'ctp-light-subtext0': '#6c6f85',
        'ctp-light-overlay2': '#7c7f93',
        'ctp-light-overlay1': '#8c8fa1',
        'ctp-light-overlay0': '#9ca0b0',
        'ctp-light-surface2': '#acb0be',
        'ctp-light-surface1': '#bcc0cc',
        'ctp-light-surface0': '#ccd0da',
        'ctp-light-base': '#eff1f5',
        'ctp-light-mantle': '#e6e9ef',
        'ctp-light-crust': '#dce0e8',
      },
    },
  },
  plugins: [],
}